<a href="https://colab.research.google.com/github/elisanathania8/Studi-Independent/blob/main/Tugas_Mandiri3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Nama : Elisa Nathania Halim,
Prodi : Sistem Informasi,
Universitas : Universitas Buana Perjuangan Karawang

In [ ]:
#nomer 1
#Data

data = {'NIK':1990022, 
        'nama':'Herman',
        'Jenis_Kelamin':'L', 
        'Alamat' : 'Tanggerang',
        'Divisi' : 'Machinery', 
        'Jabatan' : 'Manager', 
        'Gaji_Pokok' :'10.000.000'}
print(data)

data = {'NIK' : 2001077,
        'nama': 'Badar',
        'Jenis_Kelamin' : 'L',
        'Alamat' : 'Bekasi',
        'Divisi' : 'Machinery',
        'Jabatan' : 'Staff',
        'Gaji_Pokok' : '7.500.000'}
print(data)

data = {'NIK' : 2002019,
        'nama': 'Clara',
        'Jenis_Kelamin' : 'P',
        'Alamat' : 'Depok',
        'Divisi' : 'Compressor',
        'Jabatan' : 'Staff',
        'Gaji_Pokok' : '7.000.000'}
print(data)

data = {'NIK' : 2002081,
        'nama': 'Rista',
        'Jenis_Kelamin' : 'P',
        'Alamat' : 'Bogor',
        'Divisi' : 'QC',
        'Jabatan' : 'Staff',
        'Gaji_Pokok' : '6.500.000'}
print(data)

data = {'NIK' : 2005099,
        'nama': 'Riani',
        'Jenis_Kelamin' : 'P',
        'Alamat' : 'Bekasi',
        'Divisi' : 'QC',
        'Jabatan' : 'Operator',
        'Gaji_Pokok' : '6.000.000'}
print(data)        

data = {'NIK' : 2006003,
        'nama': 'Afif',
        'Jenis_Kelamin' : 'L',
        'Alamat' : 'Karawang',
        'Divisi' : 'Compressor',
        'Jabatan' : 'Operator',
        'Gaji_Pokok' : '5.500.000'}
print(data)

data = {'NIK' : 2006104,
        'nama': 'Riven',
        'Jenis_Kelamin' : 'L',
        'Alamat' : 'Tanggerang',
        'Divisi' : 'Compressor',
        'Jabatan' : 'Operator',
        'Gaji_Pokok' : '5.500.000'}
print(data)

data = {'NIK' : 2008160,
        'nama': 'Endah',
        'Jenis_Kelamin' : 'P',
        'Alamat' : 'Jakarta',
        'Divisi' : 'Machinery',
        'Jabatan' : 'Operator',
        'Gaji_Pokok' : '5.000.000'}
print(data)

{'NIK': 1990022, 'nama': 'Herman', 'Jenis_Kelamin': 'L', 'Alamat': 'Tanggerang', 'Divisi': 'Machinery', 'Jabatan': 'Manager', 'Gaji_Pokok': '10.000.000'}
{'NIK': 2001077, 'nama': 'Badar', 'Jenis_Kelamin': 'L', 'Alamat': 'Bekasi', 'Divisi': 'Machinery', 'Jabatan': 'Staff', 'Gaji_Pokok': '7.500.000'}
{'NIK': 2002019, 'nama': 'Clara', 'Jenis_Kelamin': 'P', 'Alamat': 'Depok', 'Divisi': 'Compressor', 'Jabatan': 'Staff', 'Gaji_Pokok': '7.000.000'}
{'NIK': 2002081, 'nama': 'Rista', 'Jenis_Kelamin': 'P', 'Alamat': 'Bogor', 'Divisi': 'QC', 'Jabatan': 'Staff', 'Gaji_Pokok': '6.500.000'}
{'NIK': 2005099, 'nama': 'Riani', 'Jenis_Kelamin': 'P', 'Alamat': 'Bekasi', 'Divisi': 'QC', 'Jabatan': 'Operator', 'Gaji_Pokok': '6.000.000'}
{'NIK': 2006003, 'nama': 'Afif', 'Jenis_Kelamin': 'L', 'Alamat': 'Karawang', 'Divisi': 'Compressor', 'Jabatan': 'Operator', 'Gaji_Pokok': '5.500.000'}
{'NIK': 2006104, 'nama': 'Riven', 'Jenis_Kelamin': 'L', 'Alamat': 'Tanggerang', 'Divisi': 'Compressor', 'Jabatan': 'Operato

In [ ]:
import numpy as np

In [ ]:
#nomer 2
a = np.array([[1,2],
              [4,5],
              [7,8]])
print(a, '\n')
print(a[2:, :2])

[[1 2]
 [4 5]
 [7 8]] 

[[7 8]]


In [ ]:
#nomer3
a = np.array([[1,6,9],
              [2,5,8]])
print(a, '\n')
print(a[:2, 1:2], '\n')


[[1 6 9]
 [2 5 8]] 

[[6]
 [5]] 



In [ ]:
#nomer 4
a = np.array([[4,3,8],
              [7,2,5],
              [6,1,9]])
print(a, '\n')
print(a[1:,1:2])

[[4 3 8]
 [7 2 5]
 [6 1 9]] 

[[2]
 [1]]


In [ ]:
b = np.array([[4,3,8],
              [7,2,5],
              [6,1,9]])
print(b, '\n')
print(b[:1, 1:])

[[4 3 8]
 [7 2 5]
 [6 1 9]] 

[[3 8]]


In [ ]:
#nomer 5

a = np.array([[23,35,93,87],
              [92,44,11,83],
              [40,12,46,28],
              [73,67,65,32]])
print(a, '\n')
print(a[1:2,1:])

[[23 35 93 87]
 [92 44 11 83]
 [40 12 46 28]
 [73 67 65 32]] 

[[44 11 83]]


In [ ]:
b = np.array([[23,35,93,87],
              [92,44,11,83],
              [40,12,46,28],
              [73,67,65,32]])
print(b, '\n')
print(b[2:4,1:3])

[[23 35 93 87]
 [92 44 11 83]
 [40 12 46 28]
 [73 67 65 32]] 

[[12 46]
 [67 65]]


In [ ]:
c = np.array([[23,35,93,87],
              [92,44,11,83],
              [40,12,46,28],
              [73,67,65,32]])
print(c, '\n')
print(c[1:4,1:])

[[23 35 93 87]
 [92 44 11 83]
 [40 12 46 28]
 [73 67 65 32]] 

[[44 11 83]
 [12 46 28]
 [67 65 32]]


In [ ]:
d = np.array([[23,35,93,87],
              [92,44,11,83],
              [40,12,46,28],
              [73,67,65,32]])
print(d, '\n')
print(d[1:3,:2])

[[23 35 93 87]
 [92 44 11 83]
 [40 12 46 28]
 [73 67 65 32]] 

[[92 44]
 [40 12]]


In [ ]:
e = np.array([[23,35,93,87],
              [92,44,11,83],
              [40,12,46,28],
              [73,67,65,32]])
print(e, '\n')
print(e[:2,:3])

[[23 35 93 87]
 [92 44 11 83]
 [40 12 46 28]
 [73 67 65 32]] 

[[23 35 93]
 [92 44 11]]


In [ ]:
f = np.array([[23,35,93,87],
              [92,44,11,83],
              [40,12,46,28],
              [73,67,65,32]])
print(f, '\n')
print(f[1:,1:2])

[[23 35 93 87]
 [92 44 11 83]
 [40 12 46 28]
 [73 67 65 32]] 

[[44]
 [12]
 [67]]
